import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import Nav1 from "../components/Nav1";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Nav1 />
      <NavBar />
      <div className="">{children}</div> <Toaster />
      <Footer />
    </main>
  );
}
